export const DEPARTMENTS = [
    "Department of Athletics, Physical Education and Recreation",
    "Doerr School of Sustainability",
    "Graduate School of Business",
    "Graduate School of Education",
    "Law School",
    "Office of Vice Provost for Undergraduate Education",
    "Program in Writing and Rhetoric",
    "SLAC National Accelerator Laboratory",
    "School of Engineering",
    "School of Humanities & Sciences",
    "School of Medicine",
    "Stanford Program in Berlin",
    "Stanford Program in Florence",
    "Stanford Program in Madrid",
    "Stanford Program in Oxford",
    "Stanford Program in Paris",
    "Stanford in New York",
    "Structured Liberal Education"
];

export const DEPARTMENTS_TO_SUBJECTS = {
    "Department of Athletics, Physical Education and Recreation": [
        ["ATHLETIC", "Athletics and Club Sports"],
        ["HORSE", "Horse"],
        ["OUTDOOR", "Outdoor Education"],
        ["PHYSWELL", "Physical Wellness"]
    ],
    "Doerr School of Sustainability": [
        ["EARTHSYS", "Earth Systems"],
        ["EBS", "Environmental Behavioral Science"],
        ["ENERGY", "Energy Science and Engineering"],
        ["ENVRES", "Environment and Resources"],
        ["EPS", "Earth and Planetary Sciences"],
        ["ESS", "Earth System Science"],
        ["GEOPHYS", "Geophysics"],
        ["GEP", "Global Environmental Policy"],
        ["OCEANS", "Oceans"],
        ["SUST", "Sustainability Science & Practice"],
        ["SUSTAIN", "Sustainability"]
    ],
    "Graduate School of Business": [
        ["ACCT", "Accounting"],
        ["BUSGEN", "Business General Pathways"],
        ["FINANCE", "Finance"],
        ["GSBGEN", "GSB General and Interdisciplinary"],
        ["GSBGID", "GSB Interdisciplinary"],
        ["HRMGT", "Human Resource Management"],
        ["MGTECON", "Economic Analysis and Policy"],
        ["MKTG", "Marketing"],
        ["OB", "Organizational Behavior"],
        ["OIT", "Operations Information and Technology"],
        ["POLECON", "Political Economics"],
        ["STRAMGT", "Strategic Management"]
    ],
    "Graduate School of Education": [
        ["EDUC", "Education"]
    ],
    "Law School": [
        ["LAW", "Law"],
        ["LAWGEN", "LAW GENERAL"]
    ],
    "Office of Vice Provost for Undergraduate Education": [
        ["COLLEGE", "Civic, Liberal, and Global Education"],
        ["CTL", "Center for Teaching and Learning"],
        ["ITALIC", "Immersion in the Arts"],
        ["ORALCOMM", "Oral Communication"],
        ["RESPROG", "Residential Programs"],
        ["UAR", "Undergraduate Advising and Research"]
    ],
    "Program in Writing and Rhetoric": [
        ["PWR", "Program in Writing and Rhetoric"]
    ],
    "SLAC National Accelerator Laboratory": [
        ["PHOTON", "Photon Science, SLAC"]
    ],
    "School of Engineering": [
        ["AA", "Aeronautics and Astronautics"],
        ["BIOE", "Bioengineering"],
        ["CEE", "Civil and Environmental Engineering"],
        ["CHEMENG", "Chemical Engineering"],
        ["CME", "Computational and Mathematical Engineering"],
        ["CS", "Computer Science"],
        ["DESIGN", "Design"],
        ["EE", "Electrical Engineering"],
        ["ENGR", "Engineering"],
        ["MATSCI", "Materials Science & Engineering"],
        ["ME", "Mechanical Engineering"],
        ["MS&E", "Management Science & Engineering"]
    ],
    "School of Humanities & Sciences": [
        ["AFRICAAM", "African and African American Studies"],
        ["AMHRLANG", "Amharic Language"],
        ["AMSTUD", "American Studies"],
        ["ANTHRO", "Anthropology"],
        ["APPPHYS", "Applied Physics"],
        ["ARABLANG", "Arabic Language"],
        ["ARCHLGY", "Archaeology"],
        ["ARMELANG", "Armenian Language"],
        ["ARTHIST", "Art History"],
        ["ARTSINST", "Arts Institute"],
        ["ARTSTUDI", "Art Studio"],
        ["ASLLANG", "American Sign Language"],
        ["ASNAMST", "Asian American Studies"],
        ["BIO", "Biology"],
        ["CHEM", "Chemistry"],
        ["CHILATST", "Chicana/o - Latina/o Studies"],
        ["CHINA", "China"],
        ["CHINLANG", "Chinese Language"],
        ["CLASSICS", "Classics"],
        ["COMM", "Communication"],
        ["COMPLIT", "Comparative Literature"],
        ["CSRE", "Comparative Studies in Race and Ethnicity"],
        ["CZECLANG", "Czech Language"],
        ["DANCE", "Dance"],
        ["DATASCI", "Data Science"],
        ["DDRL", "Democracy, Devlopment and the Rule of Law"],
        ["DLCL", "Division of Languages, Cultures, and Literatures"],
        ["EALC", "East Asian Languages and Cultures"],
        ["EASTASN", "East Asian Studies"],
        ["ECON", "Economics"],
        ["ENGLISH", "English"],
        ["ESOLLANG", "English for Speakers of Other Languages"],
        ["ETHICSOC", "Ethics in Society"],
        ["FEMGEN", "Feminist, Gender, and Sexuality Studies"],
        ["FILILANG", "Filipino Language"],
        ["FILMEDIA", "Film and Media Studies"],
        ["FILMPROD", "Film Production"],
        ["FRENCH", "French"],
        ["FRENLANG", "French Language"],
        ["GERLANG", "German Language"],
        ["GERMAN", "German Studies"],
        ["GLOBAL", "Global Studies"],
        ["GREELANG", "Modern Greek Language"],
        ["HAITLANG", "Haitian Creole Language"],
        ["HAWALANG", "Hawaiian Language"],
        ["HEBRLANG", "Hebrew Language"],
        ["HINDLANG", "Hindi Language"],
        ["HISTORY", "History"],
        ["HPS", "History and Philosophy of Science"],
        ["HUMBIO", "Human Biology"],
        ["HUMCORE", "Humanities Core"],
        ["HUMRTS", "Human Rights"],
        ["IGBOLANG", "Igbo Language"],
        ["IIS", "International Security Studies"],
        ["ILAC", "Iberian and Latin American Cultures"],
        ["INTLPOL", "International Policy"],
        ["INTNLREL", "International Relations"],
        ["ITALIAN", "Italian"],
        ["ITALLANG", "Italian Language"],
        ["JAPAN", "Japan"],
        ["JAPANLNG", "Japanese Language"],
        ["JEWISHST", "Jewish Studies"],
        ["KOREA", "Korea"],
        ["KORLANG", "Korean Language"],
        ["LAKOTLNG", "Lakota Language"],
        ["LATINAM", "Latin American Studies"],
        ["LINGUIST", "Linguistics"],
        ["MATH", "Mathematics"],
        ["MCS", "Mathematical and Computational Science"],
        ["MLA", "Master of Liberal Arts"],
        ["MTL", "Modern Thought and Literature"],
        ["MUSIC", "Music"],
        ["NAHUALNG", "Nahuatl Language"],
        ["NATIVEAM", "Native American Studies"],
        ["NVJOLANG", "Navajo Language"],
        ["PERSLANG", "Persian Language"],
        ["PHIL", "Philosophy"],
        ["PHYSICS", "Physics"],
        ["POLISCI", "Political Science"],
        ["POLSHLNG", "Polish Language"],
        ["PORTLANG", "Portuguese Language"],
        ["PSYCH", "Psychology"],
        ["PUBLPOL", "Public Policy"],
        ["PUNJLANG", "Punjabi Language"],
        ["QUECHLNG", "Quechua Language"],
        ["REES", "Russian, East European and Eurasian Studies"],
        ["RELIGST", "Religious Studies"],
        ["RUSSLANG", "Russian Language"],
        ["SAMOALNG", "Samoan Language"],
        ["SIW", "Stanford in Washington"],
        ["SLAVIC", "Slavic Studies"],
        ["SNSKTLNG", "Sanskrit Language"],
        ["SOC", "Sociology"],
        ["SPANLANG", "Spanish Language"],
        ["STATS", "Statistics"],
        ["STS", "Science, Technology, and Society"],
        ["SWAHLANG", "Swahili Language"],
        ["SYMSYS", "Symbolic Systems"],
        ["TAPS", "Theater and Performance Studies"],
        ["TELULANG", "Telugu Language"],
        ["TIBETLNG", "Tibetan Language"],
        ["TIGRYLNG", "Tigrinya Language"],
        ["TURKLANG", "Turkish Language"],
        ["TWILANG", "Twi Language"],
        ["UKRNLANG", "Ukrainian Language"],
        ["URBANST", "Urban Studies"],
        ["URDULANG", "Urdu Language"],
        ["VIETLANG", "Vietnamese Language"],
        ["YDDSHLNG", "Yiddish Language"],
        ["YORULANG", "Yoruba Language"]
    ],
    "School of Medicine": [
        ["ANES", "Anesthesia"],
        ["BIOC", "Biochemistry"],
        ["BIOPHYS", "Biophysics"],
        ["BIOS", "Biosciences Interdisciplinary"],
        ["BMDS", "Biomedical Data Sciences"],
        ["BMP", "Biomedical Physics"],
        ["CBIO", "Cancer Biology"],
        ["CHPR", "Community Health & Prevention Research"],
        ["CIM", "Clinical Informatics Management"],
        ["COMPMED", "Comparative Medicine"],
        ["CSB", "Chemical and Systems Biology"],
        ["CTS", "Cardiothoracic Surgery"],
        ["DBIO", "Developmental Biology"],
        ["DERM", "Dermatology"],
        ["EMED", "Emergency Medicine"],
        ["EPI", "Epidemiology"],
        ["FAMMED", "Family and Community Medicine"],
        ["GENE", "Genetics"],
        ["HRP", "Health Research and Policy"],
        ["IMMUNOL", "Immunology"],
        ["INDE", "Medicine Interdisciplinary"],
        ["MCP", "Molecular and Cellular Physiology"],
        ["MED", "Medicine"],
        ["MI", "Microbiology and Immunology"],
        ["NBIO", "Neurobiology"],
        ["NENS", "Neurology and Neurological Sciences"],
        ["NEPR", "Neurosciences Program"],
        ["NSUR", "Neurosurgery"],
        ["OBGYN", "Obstetrics and Gynecology"],
        ["OPHT", "Ophthalmology"],
        ["ORTHO", "Orthopaedic Surgery"],
        ["OTOHNS", "Otolaryngology"],
        ["PAS", "Physician Assistant Studies"],
        ["PATH", "Pathology"],
        ["PEDS", "Pediatrics"],
        ["PSYC", "Psychiatry"],
        ["RAD", "Radiology"],
        ["RADO", "Radiation Oncology"],
        ["SBIO", "Structural Biology"],
        ["SOMGEN", "School of Medicine General"],
        ["STEMREM", "Stem Cell Biology and Regenerative Medicine"],
        ["SURG", "Surgery"],
        ["TRAM", "Translational Res and App Med"],
        ["UROL", "Urology"]
    ],
    "Stanford Program in Berlin": [
        ["OSPBER", "Stanford Program in Berlin"]
    ],
    "Stanford Program in Florence": [
        ["OSPFLOR", "Stanford Program in Florence"]
    ],
    "Stanford Program in Madrid": [
        ["OSPMADRD", "Stanford Program in Madrid"]
    ],
    "Stanford Program in Oxford": [
        ["OSPOXFRD", "Stanford Program in Oxford"]
    ],
    "Stanford Program in Paris": [
        ["OSPPARIS", "Stanford Program in Paris"]
    ],
    "Stanford in New York": [
        ["SINY", "Stanford in New York"]
    ],
    "Structured Liberal Education": [
        ["SLE", "Structured Liberal Education"]
    ]
};