-- Seed initial job data for development/demo
insert into public.jobs (
    id,
    recruiter_id,
    title,
    company,
    location,
    type,
    salary_display,
    salary_min,
    description,
    skills,
    requirements,
    benefits,
    preferred_majors,
    preferred_grad_years,
    min_gpa,
    is_active,
    created_at
)
values
    (
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0001',
        null,
        'Software Engineer Intern',
        'Google',
        'Mountain View, CA',
        'Internship',
        '$8,000/mo',
        8000,
        'Join our team to build scalable systems and work on products used by billions of people worldwide.',
        array['Python','Java','Distributed Systems'],
        array['Currently pursuing BS/MS in Computer Science or related field','Strong coding skills in Python or Java','Experience with data structures and algorithms'],
        array['Free meals','Housing stipend','Mentorship program'],
        array['Computer Science','Electrical Engineering'],
        array['2026','2027'],
        3.50,
        true,
        now() - interval '2 days'
    ),
    (
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0002',
        null,
        'Frontend Developer',
        'Stripe',
        'San Francisco, CA',
        'Full-time',
        '$150k-$200k',
        150000,
        'Build beautiful, performant interfaces for the future of online payments.',
        array['React','TypeScript','CSS'],
        array['3+ years of frontend experience','Strong understanding of web fundamentals','Experience with design systems'],
        array['Competitive equity','Remote-friendly','Learning and development budget'],
        array['Computer Science','Mathematics'],
        array['2025','2026'],
        3.20,
        true,
        now() - interval '7 days'
    ),
    (
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0003',
        null,
        'Data Science Intern',
        'Meta',
        'Menlo Park, CA',
        'Internship',
        '$9,500/mo',
        9500,
        'Apply ML techniques to solve problems at massive scale across Facebook, Instagram, and WhatsApp.',
        array['Python','Machine Learning','SQL'],
        array['Pursuing degree in CS, Statistics, or related field','Experience with ML frameworks','Strong analytical skills'],
        array['Relocation assistance','Wellness programs','Team events'],
        array['Computer Science','Data Science','Mathematics'],
        array['2026','2027'],
        3.30,
        true,
        now() - interval '3 days'
    ),
    (
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0004',
        null,
        'Backend Engineer',
        'Airbnb',
        'Remote',
        'Full-time',
        '$140k-$180k',
        140000,
        'Design and implement services that power the global travel platform serving millions of guests.',
        array['Go','Kubernetes','SQL'],
        array['5+ years backend experience','Experience with microservices','Strong system design skills'],
        array['Travel credits','Flexible PTO','Home office setup'],
        array['Computer Science','Electrical Engineering'],
        array['2025'],
        null,
        true,
        now() - interval '5 days'
    ),
    (
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0005',
        null,
        'Product Manager Intern',
        'Microsoft',
        'Redmond, WA',
        'Internship',
        '$7,500/mo',
        7500,
        'Drive product strategy and work with engineering teams to ship features used by enterprises worldwide.',
        array['Data Analysis','Python'],
        array['Pursuing degree in any field','Strong communication skills','Technical background preferred'],
        array['Housing provided','Networking events','Full-time conversion opportunity'],
        array['Computer Science','Business Administration','Economics'],
        array['2026','2027'],
        3.00,
        true,
        now() - interval '1 day'
    ),
    (
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0006',
        null,
        'Machine Learning Engineer',
        'OpenAI',
        'San Francisco, CA',
        'Full-time',
        '$200k-$350k',
        200000,
        'Work on cutting-edge AI research and build systems that push the boundaries of machine learning.',
        array['Python','PyTorch','Machine Learning'],
        array['PhD or equivalent experience in ML/AI','Publications in top ML venues preferred','Strong engineering skills'],
        array['Compute credits','Research freedom','Top-tier compensation'],
        array['Computer Science','Mathematics','Physics'],
        array['2025','2026'],
        3.70,
        true,
        now() - interval '4 days'
    )
on conflict (id) do nothing;
