-- Seed 50 additional diverse job listings
INSERT INTO public.jobs (
    id,
    recruiter_id,
    title,
    company,
    location,
    type,
    salary_display,
    salary_min,
    description,
    skills,
    requirements,
    benefits,
    preferred_majors,
    preferred_grad_years,
    min_gpa,
    required_work_authorization,
    is_active,
    created_at
)
VALUES
    (
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0007',
        null,
        'DevOps Engineer',
        'Netflix',
        'Los Gatos, CA',
        'Full-time',
        '$160k-$220k',
        160000,
        'Build and maintain infrastructure that delivers streaming to 200M+ subscribers worldwide.',
        array['AWS','Docker','Kubernetes','Python','Terraform'],
        array['4+ years DevOps experience','Strong scripting skills','Experience with CI/CD pipelines'],
        array['Unlimited PTO','Stock options','Free Netflix subscription'],
        array['Computer Science','Information Technology'],
        array['2024','2025'],
        3.2,
        'US Citizen or Green Card',
        true,
        now() - interval '1 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0008',
        null,
        'Electrical Engineering Intern',
        'Tesla',
        'Palo Alto, CA',
        'Internship',
        '$8,500/mo',
        8500,
        'Design and test electrical systems for next-generation electric vehicles and energy products.',
        array['Circuit Design','MATLAB','CAD','Power Electronics'],
        array['Pursuing BS/MS in Electrical Engineering','Strong fundamentals in circuits and systems','Lab experience preferred'],
        array['Housing stipend','Employee vehicle discount','Mentorship program'],
        array['Electrical Engineering','Computer Engineering'],
        array['2026','2027'],
        3.4,
        'Any',
        true,
        now() - interval '2 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0009',
        null,
        'Data Scientist',
        'Spotify',
        'New York, NY',
        'Full-time',
        '$130k-$170k',
        130000,
        'Use data to understand user behavior and drive personalization for millions of music lovers.',
        array['Python','SQL','Machine Learning','Statistics','A/B Testing'],
        array['MS/PhD in quantitative field','3+ years experience in data science','Strong statistical modeling skills'],
        array['Premium Spotify account','Flexible work hours','Learning budget'],
        array['Data Science','Statistics','Computer Science','Mathematics'],
        array['2023','2024','2025'],
        3.3,
        'US Work Authorization Required',
        true,
        now() - interval '3 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0010',
        null,
        'Frontend Engineer Intern',
        'Figma',
        'San Francisco, CA',
        'Internship',
        '$9,000/mo',
        9000,
        'Build collaborative design tools used by designers and developers at the world''s best companies.',
        array['React','TypeScript','WebGL','CSS'],
        array['Pursuing degree in CS or related field','Strong JavaScript fundamentals','Portfolio of web projects'],
        array['Housing assistance','Free lunch and dinner','Design tools access'],
        array['Computer Science','Human-Computer Interaction'],
        array['2026','2027'],
        3.5,
        'Any',
        true,
        now() - interval '4 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0011',
        null,
        'Hardware Engineer',
        'Apple',
        'Cupertino, CA',
        'Full-time',
        '$150k-$200k',
        150000,
        'Design custom silicon and hardware for the next generation of Apple products.',
        array['VLSI Design','Verilog','Circuit Design','Signal Processing'],
        array['BS/MS in Electrical Engineering or Computer Engineering','Experience with chip design','Strong problem-solving skills'],
        array['Employee discounts','Comprehensive health coverage','On-site fitness'],
        array['Electrical Engineering','Computer Engineering'],
        array['2024','2025'],
        3.6,
        'US Citizen or Green Card',
        true,
        now() - interval '5 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0012',
        null,
        'Data Analyst Intern',
        'LinkedIn',
        'Sunnyvale, CA',
        'Internship',
        '$7,000/mo',
        7000,
        'Analyze user engagement data and provide insights to improve the professional network experience.',
        array['SQL','Python','Tableau','Excel'],
        array['Pursuing degree in Data Science, Statistics, or related field','Strong analytical skills','Experience with data visualization'],
        array['LinkedIn Premium','Networking events','Mentorship'],
        array['Data Science','Statistics','Business Analytics','Economics'],
        array['2026','2027'],
        3.0,
        'Any',
        true,
        now() - interval '6 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0013',
        null,
        'Security Engineer',
        'Cloudflare',
        'Austin, TX',
        'Full-time',
        '$140k-$190k',
        140000,
        'Protect the internet by building security systems that defend against DDoS attacks and vulnerabilities.',
        array['Network Security','Python','Go','Cryptography'],
        array['3+ years in security engineering','Deep understanding of network protocols','Experience with threat modeling'],
        array['Remote work','Generous equity','Conference budget'],
        array['Computer Science','Cybersecurity','Information Security'],
        array['2023','2024'],
        3.3,
        'US Work Authorization Required',
        true,
        now() - interval '7 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0014',
        null,
        'Machine Learning Intern',
        'NVIDIA',
        'Santa Clara, CA',
        'Internship',
        '$9,500/mo',
        9500,
        'Work on cutting-edge AI and deep learning projects leveraging GPU acceleration.',
        array['Python','PyTorch','CUDA','Deep Learning'],
        array['Pursuing MS/PhD in CS or related field','Strong ML fundamentals','Experience with neural networks'],
        array['GPU access','Research collaboration','Publication opportunities'],
        array['Computer Science','Electrical Engineering','Mathematics'],
        array['2026','2027','2028'],
        3.6,
        'Any',
        true,
        now() - interval '8 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0015',
        null,
        'Full Stack Developer',
        'Shopify',
        'Remote',
        'Full-time',
        '$120k-$160k',
        120000,
        'Build e-commerce solutions that empower millions of entrepreneurs around the world.',
        array['Ruby on Rails','React','PostgreSQL','GraphQL'],
        array['2+ years full stack experience','Strong web fundamentals','Experience with scalable systems'],
        array['Remote-first culture','Equipment budget','Flexible hours'],
        array['Computer Science','Software Engineering'],
        array['2024','2025'],
        3.0,
        'Any',
        true,
        now() - interval '9 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0016',
        null,
        'Embedded Systems Engineer',
        'SpaceX',
        'Hawthorne, CA',
        'Full-time',
        '$140k-$180k',
        140000,
        'Develop embedded software for rocket avionics and spacecraft control systems.',
        array['C','C++','RTOS','Embedded Linux'],
        array['BS in Computer Engineering or Electrical Engineering','Experience with embedded systems','Strong debugging skills'],
        array['Mission-driven work','Competitive compensation','Launch viewing'],
        array['Computer Engineering','Electrical Engineering','Aerospace Engineering'],
        array['2024','2025'],
        3.5,
        'US Citizen only',
        true,
        now() - interval '10 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0017',
        null,
        'UX Designer Intern',
        'Adobe',
        'San Jose, CA',
        'Internship',
        '$6,500/mo',
        6500,
        'Design intuitive user experiences for Creative Cloud applications used by millions of creators.',
        array['Figma','Adobe XD','User Research','Prototyping'],
        array['Pursuing degree in Design, HCI, or related field','Strong portfolio','Understanding of design systems'],
        array['Creative Cloud subscription','Design mentorship','Portfolio building'],
        array['Human-Computer Interaction','Design','Computer Science'],
        array['2026','2027'],
        3.0,
        'Any',
        true,
        now() - interval '11 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0018',
        null,
        'Site Reliability Engineer',
        'Uber',
        'San Francisco, CA',
        'Full-time',
        '$155k-$210k',
        155000,
        'Ensure reliability and performance of systems serving millions of rides and deliveries daily.',
        array['Go','Kubernetes','Monitoring','Linux','Distributed Systems'],
        array['5+ years in SRE or infrastructure','Experience with incident response','Strong automation skills'],
        array['Ride credits','Stock options','On-call compensation'],
        array['Computer Science','Software Engineering'],
        array['2022','2023','2024'],
        3.2,
        'US Work Authorization Required',
        true,
        now() - interval '12 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0019',
        null,
        'Robotics Software Engineer',
        'Boston Dynamics',
        'Waltham, MA',
        'Full-time',
        '$130k-$170k',
        130000,
        'Develop control algorithms and perception systems for advanced mobile robots.',
        array['C++','ROS','Computer Vision','Control Systems','Python'],
        array['MS in Robotics, CS, or related field','Experience with robot control','Strong math background'],
        array['Cutting-edge research','Publication opportunities','Relocation assistance'],
        array['Robotics','Computer Science','Mechanical Engineering','Electrical Engineering'],
        array['2024','2025'],
        3.4,
        'US Work Authorization Required',
        true,
        now() - interval '13 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0020',
        null,
        'Data Engineering Intern',
        'Snowflake',
        'San Mateo, CA',
        'Internship',
        '$8,500/mo',
        8500,
        'Build data pipelines and infrastructure for cloud-based data warehousing at scale.',
        array['SQL','Python','Apache Spark','ETL'],
        array['Pursuing degree in CS, Data Science, or related field','Experience with databases','Strong programming skills'],
        array['Housing stipend','Free meals','Full-time conversion'],
        array['Computer Science','Data Science','Information Systems'],
        array['2026','2027'],
        3.3,
        'Any',
        true,
        now() - interval '14 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0021',
        null,
        'iOS Developer',
        'Snap Inc.',
        'Los Angeles, CA',
        'Full-time',
        '$140k-$180k',
        140000,
        'Build features for Snapchat''s iOS app used by hundreds of millions of users daily.',
        array['Swift','iOS SDK','UIKit','SwiftUI'],
        array['3+ years iOS development','Published apps in App Store','Strong understanding of iOS design patterns'],
        array['Snap stock','Free lunches','Creative environment'],
        array['Computer Science','Software Engineering'],
        array['2023','2024'],
        3.1,
        'US Work Authorization Required',
        true,
        now() - interval '15 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0022',
        null,
        'Quantum Computing Researcher',
        'IBM',
        'Yorktown Heights, NY',
        'Full-time',
        '$150k-$200k',
        150000,
        'Research and develop quantum algorithms and applications for IBM Quantum systems.',
        array['Qiskit','Python','Quantum Mechanics','Linear Algebra'],
        array['PhD in Physics, CS, or related field','Deep understanding of quantum computing','Research publications'],
        array['Research freedom','Publication support','Collaborative environment'],
        array['Physics','Computer Science','Mathematics'],
        array['2023','2024','2025'],
        3.7,
        'Any',
        true,
        now() - interval '16 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0023',
        null,
        'Backend Engineer Intern',
        'Discord',
        'San Francisco, CA',
        'Internship',
        '$8,000/mo',
        8000,
        'Build scalable backend services for real-time communication serving millions of communities.',
        array['Python','Rust','PostgreSQL','Redis'],
        array['Pursuing BS/MS in Computer Science','Strong coding fundamentals','Interest in distributed systems'],
        array['Gaming setup','Nitro subscription','Team events'],
        array['Computer Science','Software Engineering'],
        array['2026','2027'],
        3.2,
        'Any',
        true,
        now() - interval '17 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0024',
        null,
        'Computer Vision Engineer',
        'Waymo',
        'Mountain View, CA',
        'Full-time',
        '$170k-$230k',
        170000,
        'Develop perception systems for autonomous vehicles using state-of-the-art computer vision.',
        array['Python','C++','Computer Vision','Deep Learning','OpenCV'],
        array['MS/PhD in CS or related field','Experience with vision systems','Strong ML background'],
        array['Autonomous vehicle rides','Top-tier compensation','Research opportunities'],
        array['Computer Science','Electrical Engineering','Robotics'],
        array['2024','2025'],
        3.6,
        'US Work Authorization Required',
        true,
        now() - interval '18 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0025',
        null,
        'Product Designer',
        'Notion',
        'Remote',
        'Full-time',
        '$120k-$160k',
        120000,
        'Design beautiful, functional interfaces for the all-in-one workspace tool.',
        array['Figma','User Research','Prototyping','Design Systems'],
        array['3+ years product design experience','Strong portfolio','Experience with SaaS products'],
        array['Remote work','Flexible hours','Generous equity'],
        array['Design','Human-Computer Interaction','Computer Science'],
        array['2023','2024'],
        3.0,
        'Any',
        true,
        now() - interval '19 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0026',
        null,
        'Chip Design Engineer',
        'AMD',
        'Austin, TX',
        'Full-time',
        '$135k-$175k',
        135000,
        'Design and verify high-performance processors and GPUs for computing and gaming.',
        array['Verilog','SystemVerilog','VLSI','Digital Design'],
        array['BS/MS in Electrical Engineering','Experience with RTL design','Knowledge of computer architecture'],
        array['Relocation assistance','Stock options','Employee discounts'],
        array['Electrical Engineering','Computer Engineering'],
        array['2024','2025'],
        3.4,
        'US Work Authorization Required',
        true,
        now() - interval '20 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0027',
        null,
        'Data Science Intern',
        'Airbnb',
        'San Francisco, CA',
        'Internship',
        '$8,500/mo',
        8500,
        'Use data to improve host and guest experiences on the global travel marketplace.',
        array['Python','R','SQL','Machine Learning','Statistics'],
        array['Pursuing MS in Data Science, Statistics, or related field','Strong statistical knowledge','Experience with experimentation'],
        array['Travel credits','Housing stipend','Team offsites'],
        array['Data Science','Statistics','Computer Science','Economics'],
        array['2026','2027'],
        3.4,
        'Any',
        true,
        now() - interval '21 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0028',
        null,
        'Cloud Solutions Architect',
        'Amazon Web Services',
        'Seattle, WA',
        'Full-time',
        '$145k-$195k',
        145000,
        'Help enterprise customers design and implement cloud architectures on AWS.',
        array['AWS','Cloud Architecture','Python','Terraform','Networking'],
        array['5+ years cloud experience','AWS certifications preferred','Strong customer-facing skills'],
        array['AWS credits','Certification support','Stock grants'],
        array['Computer Science','Information Technology'],
        array['2022','2023','2024'],
        3.1,
        'US Work Authorization Required',
        true,
        now() - interval '22 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0029',
        null,
        'Mobile Engineer Intern',
        'TikTok',
        'San Jose, CA',
        'Internship',
        '$9,000/mo',
        9000,
        'Build features for one of the world''s fastest-growing social media platforms.',
        array['React Native','iOS','Android','JavaScript'],
        array['Pursuing BS/MS in Computer Science','Mobile development experience','Strong coding skills'],
        array['Housing assistance','Free meals','Global team exposure'],
        array['Computer Science','Software Engineering'],
        array['2026','2027'],
        3.3,
        'Any',
        true,
        now() - interval '23 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0030',
        null,
        'Firmware Engineer',
        'Rivian',
        'Irvine, CA',
        'Full-time',
        '$130k-$170k',
        130000,
        'Develop firmware for electric vehicle control systems and battery management.',
        array['C','Embedded Systems','CAN Bus','Automotive Standards'],
        array['BS/MS in Computer Engineering or Electrical Engineering','Embedded software experience','Automotive experience preferred'],
        array['Vehicle discount','Equity','Outdoor activities'],
        array['Computer Engineering','Electrical Engineering'],
        array['2024','2025'],
        3.3,
        'US Work Authorization Required',
        true,
        now() - interval '24 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0031',
        null,
        'Research Scientist Intern',
        'DeepMind',
        'London, UK',
        'Internship',
        '£6,000/mo',
        6000,
        'Conduct cutting-edge AI research in reinforcement learning, neuroscience, or related areas.',
        array['Python','TensorFlow','PyTorch','Research Methodology'],
        array['Pursuing PhD in CS, ML, or related field','Strong publication record','Deep ML knowledge'],
        array['Research mentorship','Publication support','Relocation assistance'],
        array['Computer Science','Mathematics','Physics','Neuroscience'],
        array['2027','2028'],
        3.8,
        'Any',
        true,
        now() - interval '25 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0032',
        null,
        'QA Engineer',
        'Atlassian',
        'Sydney, Australia',
        'Full-time',
        'AU$100k-$130k',
        100000,
        'Ensure quality of Jira, Confluence, and other collaboration tools through comprehensive testing.',
        array['Test Automation','Selenium','Java','CI/CD'],
        array['3+ years QA experience','Experience with automation frameworks','Strong attention to detail'],
        array['Remote flexibility','Professional development','Team retreats'],
        array['Computer Science','Software Engineering'],
        array['2023','2024'],
        3.0,
        'Australian Work Rights',
        true,
        now() - interval '26 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0033',
        null,
        'Signal Processing Engineer',
        'Qualcomm',
        'San Diego, CA',
        'Full-time',
        '$125k-$165k',
        125000,
        'Develop DSP algorithms for wireless communication and mobile chipsets.',
        array['MATLAB','C','DSP','Wireless Communications'],
        array['MS in Electrical Engineering','Strong signal processing background','Experience with wireless standards'],
        array['Patent bonuses','Comprehensive benefits','Tuition reimbursement'],
        array['Electrical Engineering','Computer Engineering'],
        array['2024','2025'],
        3.5,
        'US Work Authorization Required',
        true,
        now() - interval '27 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0034',
        null,
        'Backend Developer Intern',
        'Stripe',
        'San Francisco, CA',
        'Internship',
        '$9,500/mo',
        9500,
        'Build APIs and services that process billions of dollars in online payments.',
        array['Ruby','Java','PostgreSQL','API Design'],
        array['Pursuing BS/MS in Computer Science','Strong backend fundamentals','Experience with databases'],
        array['Housing stipend','Free meals','Mentorship'],
        array['Computer Science','Software Engineering'],
        array['2026','2027'],
        3.5,
        'Any',
        true,
        now() - interval '28 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0035',
        null,
        'Game Developer',
        'Epic Games',
        'Cary, NC',
        'Full-time',
        '$110k-$150k',
        110000,
        'Develop gameplay systems and tools for Fortnite and Unreal Engine.',
        array['C++','Unreal Engine','Game Design','3D Math'],
        array['2+ years game development experience','Strong C++ skills','Shipped game titles preferred'],
        array['Game credits','Flexible hours','Creative culture'],
        array['Computer Science','Game Development','Software Engineering'],
        array['2024','2025'],
        3.0,
        'US Work Authorization Required',
        true,
        now() - interval '29 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0036',
        null,
        'Network Engineer',
        'Cisco',
        'San Jose, CA',
        'Full-time',
        '$115k-$155k',
        115000,
        'Design and implement networking solutions for enterprise and service provider customers.',
        array['Networking','BGP','OSPF','Python','Network Security'],
        array['BS in Computer Engineering or related field','CCNA/CCNP certification','3+ years networking experience'],
        array['Certification training','Stock purchase plan','Comprehensive insurance'],
        array['Computer Engineering','Electrical Engineering','Computer Science'],
        array['2023','2024'],
        3.2,
        'US Work Authorization Required',
        true,
        now() - interval '30 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0037',
        null,
        'AI Research Intern',
        'Anthropic',
        'San Francisco, CA',
        'Internship',
        '$10,000/mo',
        10000,
        'Contribute to AI safety research and help build helpful, harmless, and honest AI systems.',
        array['Python','PyTorch','Transformers','Research'],
        array['Pursuing PhD in CS or related field','Strong ML fundamentals','Research experience'],
        array['Research mentorship','Publication opportunities','Cutting-edge work'],
        array['Computer Science','Mathematics','Physics'],
        array['2027','2028'],
        3.8,
        'Any',
        true,
        now() - interval '1 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0038',
        null,
        'Database Administrator',
        'Oracle',
        'Redwood City, CA',
        'Full-time',
        '$110k-$145k',
        110000,
        'Manage and optimize database systems for enterprise customers worldwide.',
        array['Oracle DB','SQL','Performance Tuning','Backup & Recovery'],
        array['BS in Computer Science or related field','3+ years DBA experience','Oracle certification preferred'],
        array['Certification programs','Stock options','Career development'],
        array['Computer Science','Information Systems'],
        array['2023','2024'],
        3.0,
        'US Work Authorization Required',
        true,
        now() - interval '2 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0039',
        null,
        'Cybersecurity Analyst Intern',
        'Palo Alto Networks',
        'Santa Clara, CA',
        'Internship',
        '$7,500/mo',
        7500,
        'Analyze security threats and help protect enterprise networks from cyber attacks.',
        array['Network Security','Python','Threat Analysis','SIEM'],
        array['Pursuing BS/MS in Cybersecurity or CS','Understanding of security principles','Security certifications a plus'],
        array['Security training','Certification support','Mentorship'],
        array['Cybersecurity','Computer Science','Information Security'],
        array['2026','2027'],
        3.2,
        'Any',
        true,
        now() - interval '3 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0040',
        null,
        'Systems Software Engineer',
        'Red Hat',
        'Raleigh, NC',
        'Full-time',
        '$120k-$160k',
        120000,
        'Contribute to Linux kernel and open-source systems software used by enterprises globally.',
        array['C','Linux Kernel','Systems Programming','Git'],
        array['BS/MS in Computer Science','Strong systems programming skills','Open source contributions preferred'],
        array['Open source culture','Remote work','Conference attendance'],
        array['Computer Science','Computer Engineering'],
        array['2024','2025'],
        3.3,
        'US Work Authorization Required',
        true,
        now() - interval '4 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0041',
        null,
        'Data Analyst',
        'Salesforce',
        'San Francisco, CA',
        'Full-time',
        '$95k-$125k',
        95000,
        'Analyze customer data to drive insights and improve CRM platform features.',
        array['SQL','Tableau','Python','Excel'],
        array['BS in Data Science, Business Analytics, or related field','2+ years analysis experience','Strong communication skills'],
        array['Volunteer time off','Wellness reimbursement','Stock options'],
        array['Data Science','Business Analytics','Statistics','Economics'],
        array['2024','2025'],
        3.1,
        'US Work Authorization Required',
        true,
        now() - interval '5 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0042',
        null,
        'Software Engineer Intern',
        'Dropbox',
        'Remote',
        'Internship',
        '$8,000/mo',
        8000,
        'Build features for cloud storage and collaboration tools used by millions worldwide.',
        array['Python','Go','React','Distributed Systems'],
        array['Pursuing BS/MS in Computer Science','Strong programming fundamentals','Passion for building products'],
        array['Remote internship','Equipment provided','Full-time conversion'],
        array['Computer Science','Software Engineering'],
        array['2026','2027'],
        3.2,
        'Any',
        true,
        now() - interval '6 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0043',
        null,
        'RF Engineer',
        'Verizon',
        'Basking Ridge, NJ',
        'Full-time',
        '$105k-$140k',
        105000,
        'Design and optimize wireless networks for 5G deployment across the nation.',
        array['RF Engineering','5G','Network Planning','MATLAB'],
        array['BS/MS in Electrical Engineering','RF design experience','Knowledge of wireless standards'],
        array['Phone plan discount','Tuition assistance','Retirement matching'],
        array['Electrical Engineering','Telecommunications'],
        array['2024','2025'],
        3.2,
        'US Work Authorization Required',
        true,
        now() - interval '7 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0044',
        null,
        'Machine Learning Engineer',
        'Scale AI',
        'San Francisco, CA',
        'Full-time',
        '$160k-$220k',
        160000,
        'Build ML infrastructure and tools for data labeling and model training at scale.',
        array['Python','TensorFlow','PyTorch','MLOps','Kubernetes'],
        array['BS/MS in CS or related field','3+ years ML engineering','Experience with ML infrastructure'],
        array['Equity','Learning budget','Flexible PTO'],
        array['Computer Science','Data Science','Mathematics'],
        array['2023','2024'],
        3.4,
        'US Work Authorization Required',
        true,
        now() - interval '8 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0045',
        null,
        'Power Systems Engineer',
        'General Electric',
        'Schenectady, NY',
        'Full-time',
        '$95k-$125k',
        95000,
        'Design electrical power systems and grid infrastructure for renewable energy projects.',
        array['Power Systems','MATLAB','PSCAD','Renewable Energy'],
        array['BS/MS in Electrical Engineering','Power systems coursework','PE license preferred'],
        array['Pension plan','Tuition reimbursement','Relocation assistance'],
        array['Electrical Engineering','Power Engineering'],
        array['2024','2025','2026'],
        3.0,
        'US Work Authorization Required',
        true,
        now() - interval '9 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0046',
        null,
        'Software Development Engineer',
        'Amazon',
        'Seattle, WA',
        'Full-time',
        '$130k-$170k',
        130000,
        'Build scalable services for Amazon''s e-commerce platform and AWS infrastructure.',
        array['Java','Python','AWS','Distributed Systems'],
        array['BS/MS in Computer Science','Strong coding skills','Experience with large-scale systems'],
        array['Stock grants','Relocation package','Career growth'],
        array['Computer Science','Software Engineering'],
        array['2024','2025','2026'],
        3.2,
        'US Work Authorization Required',
        true,
        now() - interval '10 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0047',
        null,
        'Data Engineer',
        'Databricks',
        'San Francisco, CA',
        'Full-time',
        '$145k-$190k',
        145000,
        'Build data infrastructure and pipelines for unified analytics platform.',
        array['Spark','Scala','Python','SQL','Distributed Systems'],
        array['BS/MS in CS or related field','3+ years data engineering','Experience with big data technologies'],
        array['Equity','Learning stipend','Flexible work'],
        array['Computer Science','Data Science','Information Systems'],
        array['2023','2024'],
        3.3,
        'US Work Authorization Required',
        true,
        now() - interval '11 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0048',
        null,
        'ASIC Design Engineer',
        'Intel',
        'Hillsboro, OR',
        'Full-time',
        '$130k-$170k',
        130000,
        'Design and verify custom integrated circuits for next-generation processors.',
        array['Verilog','ASIC Design','Timing Analysis','Synthesis'],
        array['MS in Electrical Engineering','ASIC design experience','Knowledge of design tools'],
        array['Employee stock purchase','Relocation','On-site amenities'],
        array['Electrical Engineering','Computer Engineering'],
        array['2024','2025'],
        3.5,
        'US Work Authorization Required',
        true,
        now() - interval '12 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0049',
        null,
        'Product Manager Intern',
        'Slack',
        'San Francisco, CA',
        'Internship',
        '$7,500/mo',
        7500,
        'Drive product strategy for workplace collaboration features used by Fortune 500 companies.',
        array['Product Management','Data Analysis','SQL','User Research'],
        array['Pursuing MBA or technical degree','Strong analytical skills','Technical background helpful'],
        array['Housing assistance','Networking','PM mentorship'],
        array['Computer Science','Business Administration','Economics'],
        array['2026','2027'],
        3.3,
        'Any',
        true,
        now() - interval '13 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0050',
        null,
        'Computer Graphics Engineer',
        'Pixar',
        'Emeryville, CA',
        'Full-time',
        '$125k-$165k',
        125000,
        'Develop rendering software and tools for creating animated feature films.',
        array['C++','Computer Graphics','OpenGL','Linear Algebra'],
        array['MS in CS with graphics focus','Strong math background','Experience with rendering'],
        array['Creative environment','Film screenings','On-site amenities'],
        array['Computer Science','Computer Graphics','Mathematics'],
        array['2024','2025'],
        3.5,
        'US Work Authorization Required',
        true,
        now() - interval '14 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0051',
        null,
        'Bioinformatics Engineer',
        'Illumina',
        'San Diego, CA',
        'Full-time',
        '$110k-$145k',
        110000,
        'Develop computational tools for genomic sequencing and analysis.',
        array['Python','R','Bioinformatics','Statistics','Genomics'],
        array['MS/PhD in Bioinformatics, CS, or related field','Experience with genomic data','Strong programming skills'],
        array['Research collaboration','Publication support','Health benefits'],
        array['Bioinformatics','Computer Science','Biology','Computational Biology'],
        array['2024','2025'],
        3.4,
        'US Work Authorization Required',
        true,
        now() - interval '15 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0052',
        null,
        'Platform Engineer',
        'Twilio',
        'Remote',
        'Full-time',
        '$135k-$175k',
        135000,
        'Build developer tools and APIs for cloud communications platform.',
        array['Go','Kubernetes','AWS','API Design'],
        array['3+ years platform engineering','Experience with cloud infrastructure','Strong API design skills'],
        array['Remote-first','Equity','Home office budget'],
        array['Computer Science','Software Engineering'],
        array['2023','2024'],
        3.1,
        'Any',
        true,
        now() - interval '16 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0053',
        null,
        'Analog IC Design Engineer',
        'Texas Instruments',
        'Dallas, TX',
        'Full-time',
        '$115k-$150k',
        115000,
        'Design analog and mixed-signal integrated circuits for industrial and automotive applications.',
        array['Analog Design','Cadence','Circuit Analysis','Layout'],
        array['MS in Electrical Engineering','Analog IC design experience','Strong circuit fundamentals'],
        array['Relocation assistance','Patent bonuses','Comprehensive benefits'],
        array['Electrical Engineering'],
        array['2024','2025'],
        3.4,
        'US Work Authorization Required',
        true,
        now() - interval '17 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0054',
        null,
        'Software Engineer Intern',
        'Roblox',
        'San Mateo, CA',
        'Internship',
        '$8,500/mo',
        8500,
        'Build platform features for the metaverse where millions create and play together.',
        array['C++','Lua','Game Development','Distributed Systems'],
        array['Pursuing BS/MS in Computer Science','Strong C++ skills','Passion for gaming'],
        array['Robux credits','Gaming setup','Team events'],
        array['Computer Science','Software Engineering','Game Development'],
        array['2026','2027'],
        3.2,
        'Any',
        true,
        now() - interval '18 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0055',
        null,
        'Applied Scientist',
        'Microsoft Research',
        'Redmond, WA',
        'Full-time',
        '$155k-$205k',
        155000,
        'Conduct research in AI, ML, and computer science with real-world impact.',
        array['Python','Machine Learning','Research','Statistics'],
        array['PhD in CS or related field','Strong publication record','Research experience'],
        array['Research freedom','Publication support','Collaborative environment'],
        array['Computer Science','Mathematics','Statistics'],
        array['2023','2024','2025'],
        3.7,
        'US Work Authorization Required',
        true,
        now() - interval '19 days'
    )
    ,(
        '9f7ab991-ef45-4d4f-a8a8-4c75c4df0056',
        null,
        'Business Intelligence Analyst',
        'Walmart',
        'Bentonville, AR',
        'Full-time',
        '$85k-$110k',
        85000,
        'Analyze retail data to optimize supply chain, pricing, and inventory management.',
        array['SQL','Tableau','Power BI','Python'],
        array['BS in Business Analytics, Data Science, or related field','2+ years BI experience','Retail experience a plus'],
        array['Employee discount','401k matching','Relocation assistance'],
        array['Business Analytics','Data Science','Information Systems','Economics'],
        array['2024','2025'],
        3.0,
        'US Work Authorization Required',
        true,
        now() - interval '20 days'
    )
ON CONFLICT (id) DO NOTHING;